### ISSUE TITLE
Feedback on the ALPHA hyperplance concept

### ISSUE THREAD

**Issue by novoid** [kra-mo/hyperplane#2]
Hi,

Congrats for exploring the world of non-hierarchical file management methods and thanks for your prototype!

With the experience from [tagstore (a research software to explore aspects of tagging files](https://karl-voit.at/tagstore/) which was part of [my PhD on that topic](https://karl-voit.at/tagstore/en/papers.shtml)) and [filetags (my current method)](https://karl-voit.at/managing-digital-photographs/) I'd like to give some feedback on the concept.

First, a few comments on the README file from [your repository](https://github.com/kra-mo/Hyperplane).

> The problem is that current methods for tagging files are OS-, file system- or application-specific and not portable.

As far as I understood your concept, your app offers its non-hierarchical file retrieval method in an application-specific way which is not available when using File Open/Save dialoges in applications or other file managers. So I would suggest that you should mention that your solution may not address the issue of having application-specific interfaces for tags.

> Hyperplane stores its 'tags' (called categories) on disk as regular directories.

To my understanding, "tags" are different from "categories".

While one item may be categorized with one single category, it may have multiple tags which offers multi-classification. Therefore, I'd overthink your naming scheme before settling with names that might cause misunderstanding.

> File A tagged 'Pictures', 'Art' and 'Animals' would be stored at `/Pictures/Art/Animals/` on disk.

I do have food for thought for you. My filetags method implements a concept I named "TagTrees". You can learn about it in [this article](https://karl-voit.at/managing-digital-photographs/) or [in the README of filetags](https://github.com/novoid/filetags#tagtrees). Basically, it provides access to files tagged with 'Pictures', 'Art' and 'Animals' in paths that reflect all different permutations of those three tags:

-   Pictures/Art/Animals/
-   Pictures/Animals/Art/
-   Art/Pictures/Animals/
-   Art/Animals/Pictures/
-   Animals/Pictures/Art/
-   Animals/Art/Pictures/

This allows for not having to remember absolute paths or orders of tagging.

> The app keeps track of the list of categories in a `.hyperplane` file at the root of the Hyperplane directory.

You did not specify where the tags-to-file-relations are stored. I assume it is in this `.hyperplane` file.

If so, you introduced fragile tag-to-file-relations: if a file gets renamed, you'll probably lose the association to the tags.

> The name
> 
> <https://en.wikipedia.org/wiki/Hyperplane>
> 
> It is subject to change.

Yes, you should definitely change it as soon as possible. "Hyperplane" is a well-known concept already and you'll get a hard time to be found via search engines when you try to overwrite that concept name.

In general, I'm personally still not convinced of any file store and retrieval UI which offers great assistant but is only specific to that single interface.

If you might want to overthink this approach to truly assist an independent method, you might as well take any existing method and offer an additional UI for it. So you could adapt your tool to visualize files stored in the concept of [TagSpaces](https://www.tagspaces.org/), [denote](https://github.com/protesilaos/denote), [fs-curator](https://github.com/unreadablewxy/fs-curator) (I'm not very familiar with this) or even my filetags. The latter would have the advantage that there's no specific GUI tool which could serve as an alternative to TagTrees sub-hierarchy generation (which could take many resources especially on NTFS-systems) available at the moment, if you don't count [filetags.el](https://github.com/beutelma/filetags.el) (for Emacs [dired](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html)).

Whatever you do, **have fun** working on your project, exploring the world of non-hierarchical file storage and retrieval methods.

**Comment by kra-mo** [comment]
Hi, thanks for the feedback!

> As far as I understood your concept, your app offers its non-hierarchical file retrieval method in an application-specific way which is not available when using File Open/Save dialoges in applications or other file managers. So I would suggest that you should mention that your solution may not address the issue of having application-specific interfaces for tags.

While the non-hierarchical nature is not currently available outside the app, the categories themselves still are, just in a hierarchical way as they are represented by directories. I do plan to offer a FUSE filesystem to be able to access them in any order outside the app too. :)

> To my understanding, "tags" are different from "categories".
>
> While one item may be categorized with one single category, it may have multiple tags which offers multi-classification. Therefore, I'd overthink your naming scheme before settling with names that might cause misunderstanding.

Yes, the names are not final. I was reluctant to call them tags specifically, because a file that is in a category may not also be in a folder. Library may be a better term, but I'm still undecided.

> I do have food for thought for you. My filetags method implements a concept I named "TagTrees". You can learn about it in [this article](https://karl-voit.at/managing-digital-photographs/) or [in the README of filetags](https://github.com/novoid/filetags#tagtrees). Basically, it provides access to files tagged with 'Pictures', 'Art' and 'Animals' in paths that reflect all different permutations of those three tags

That is interesting, but the idea with Hyperplane was that you would use the application as your primary file manager and since it abstracts away the paths, it would define the path for each combination of tags for itself. But it might not hurt to try this method either.

> You did not specify where the tags-to-file-relations are stored. I assume it is in this .hyperplane file.
>
> If so, you introduced fragile tag-to-file-relations: if a file gets renamed, you'll probably lose the association to the tags.

The relations are defined by the files' location inside directories. The only thing in the `.hyperplane` file is the possible tags which would be represented by directories.

So a `.hyperplane` file would look like:

```
Pictures
Music
Videos
Art
Animals
Birds
```

The only way relations can break is if a directory that represents a tag is moved or renamed, but that is assumed to be intentional on the user's part. So the file can not ever become stale.

> In general, I'm personally still not convinced of any file store and retrieval UI which offers great assistant but is only specific to that single interface.

This is why I wanted to keep the method very simple. It is basically just additional aid on top of a method of organizing files that you could adapt manually in any file manager, so no information gets locked inside the app.

> Whatever you do, have fun working on your project, exploring the world of non-hierarchical file storage and retrieval methods.

Thanks :)

I will look into tagstore and filetags, they seem interesting.
